import { useState } from "react";
import Icon from "../shared/Icon";
import { MISSED_DECISIONS, csvDownload } from "../shared/demo";
import { useData } from "../shared/store";
import { Empty, Field, Modal, Note, Panel, Pill } from "../shared/ui";
import { Metric, PageHead } from "./TeacherUI";
import { useScope } from "./TeacherApp";

type Report = { id: string; title: string; detail: string; icon: string };
const REPORTS: Report[] = [
  { id: "completion", icon: "graduation", title: "Section completion", detail: "Module and phase completion for every eligible learner in this section." },
  { id: "progress", icon: "users", title: "Token-level learning progress", detail: "Per-token completion, best and latest scores, and participation state." },
  { id: "misconceptions", icon: "assessment", title: "Quiz misconceptions", detail: "Questions most often missed, grouped by approved answer mappings." },
  { id: "decisions", icon: "clock", title: "Simulation decisions", detail: "Decision accuracy and data quality per practical attempt." },
  { id: "published", icon: "check", title: "Published grades", detail: "Teacher grades and feedback already visible to learners and linked parents." },
  { id: "pending", icon: "bell", title: "Pending reviews", detail: "Attempts submitted to you but not yet reviewed." },
  { id: "revision", icon: "curriculum", title: "Recommended revision topics", detail: "Learning needs to revisit with the whole section." },
];

function columnsOf(report: Report) {
  if (report.id === "completion" || report.id === "progress") return ["Token", "Participation", "Consent", "Assent", "Modules completed", "Average score", "Last activity"];
  if (report.id === "misconceptions" || report.id === "revision") return ["Module", "Learning need", "Share of learners"];
  if (report.id === "published") return ["Token", "Module", "Teacher grade", "State", "Feedback"];
  if (report.id === "pending") return ["Token", "Module", "Automatic practical", "Data quality"];
  return ["Token", "Module", "Practical", "Decision accuracy", "Reaction context", "Data quality"];
}

export function TeacherReports() {
  const store = useData();
  const { users, assessments, settings, refreshed, log, say } = store;
  const scope = useScope();
  const [last, setLast] = useState("");
  const roster = users.filter(user => user.role === "Student" && user.section === scope.sectionId);
  const rows = assessments.filter(row => row.sectionId === scope.sectionId);

  function header(title: string, columns: string[]) {
    return [
      [`SafetyQuest teacher report: ${title}`],
      [`Section scope: ${store.sectionOf(scope.sectionId)} (assigned sections only)`],
      [`Reporting period: ${settings.term}`],
      [`Generated by: ${scope.teacherName}`],
      [`Generated: ${refreshed}`],
      [`Scoring versions: the lesson is a prerequisite, not a score · practical pass mark ${settings.practicalPass}%`],
      [`Completeness: ${roster.filter(student => student.status !== "Active").length} token not yet active; ${rows.filter(row => row.quality === "Interrupted").length} interrupted attempts excluded from timing`],
      [],
      columns,
    ];
  }

  // One row set per report, so a card can show its size before anything downloads.
  function body(report: Report): (string | number)[][] {
    if (report.id === "completion" || report.id === "progress") {
      return roster.map(student => [student.name, student.status, student.consent ? "Verified" : "Not verified", student.assent ? "Given" : "Not given", `${student.completed}/15`, `${student.score}%`, student.lastActive ?? "—"]);
    }
    if (report.id === "misconceptions" || report.id === "revision") {
      return MISSED_DECISIONS.map(item => [item.module, item.decision, `${item.share}%`]);
    }
    if (report.id === "published") {
      return rows.filter(row => row.review === "Published" || row.review === "Revised").map(row => [store.nameOf(row.studentId), store.moduleOf(row.moduleId), `${row.grade ?? row.practical}%`, row.review, row.feedback ?? ""]);
    }
    if (report.id === "pending") {
      return rows.filter(row => row.review === "Awaiting review").map(row => [store.nameOf(row.studentId), store.moduleOf(row.moduleId), `${row.practical}%`, row.quality]);
    }
    return rows.map(row => [store.nameOf(row.studentId), store.moduleOf(row.moduleId), `${row.practical}%`, `${row.accuracy}%`, row.quality === "Complete" ? `${row.reaction.toFixed(1)}s` : "Unavailable", row.quality]);
  }

  function generate(report: Report) {
    const stamp = new Date().toISOString().slice(0, 10);
    csvDownload(`safetyquest-${scope.sectionId}-${report.id}-${stamp}.csv`, [...header(report.title, columnsOf(report)), ...body(report)]);
    log("Report generated", `${report.title} · ${store.sectionOf(scope.sectionId)} · by ${scope.teacherName}`);
    say(`${report.title} downloaded for ${store.sectionOf(scope.sectionId)}.`);
    setLast(report.title);
  }

  return <div className="tc-page">
    <PageHead icon="reports" eyebrow="Reports" title={store.sectionOf(scope.sectionId)}>
      Exports cover this section only — you cannot export a section you are not assigned to. Every file carries its scope, timestamp, scoring versions, and completeness notes in the first rows.
    </PageHead>

    <div className="tc-reports">
      {REPORTS.map(report => {
        const count = body(report).length;
        return <article key={report.id} className="tc-report">
          <header><span className="tc-report-icon"><Icon name={report.icon} /></span><h3>{report.title}</h3></header>
          <p>{report.detail}</p>
          <dl className="tc-facts">
            <div><dt>Rows</dt><dd>{count}</dd></div>
            <div><dt>Columns</dt><dd>{columnsOf(report).length}</dd></div>
          </dl>
          <button type="button" className="sa-ghost" onClick={() => generate(report)} disabled={count === 0}>
            <Icon name="download" />{count === 0 ? "Nothing to export" : `Generate CSV · ${count} rows`}
          </button>
        </article>;
      })}
    </div>

    {last && <Note>Last generated in this session: {last}. A parent receives a child-specific report only — never a full class export.</Note>}
  </div>;
}

export function TeacherAnnouncements() {
  const store = useData();
  const { announcements, setAnnouncements, log, say } = store;
  const scope = useScope();
  const [composing, setComposing] = useState(false);
  const audience = store.sectionOf(scope.sectionId);
  const mine = announcements.filter(item => scope.mySections.some(section => section.name === item.audience));
  const fromAdmin = announcements.filter(item => !scope.mySections.some(section => section.name === item.audience));

  return <div className="tc-page">
    <PageHead icon="announcements" eyebrow="Announcements" title={audience}
      actions={<button type="button" className="sa-primary" onClick={() => setComposing(true)}><Icon name="plus" />New announcement</button>}>
      You can publish to your assigned sections only. Direct private chat is not part of this release, and no announcement carries a token, a name, or a result.
    </PageHead>

    <Panel title="Your section announcements" icon="announcements" note={`Published to ${audience} and its linked guardians where enabled.`} wide>
      {mine.length === 0 ? <Empty text="You have not published a section announcement yet." /> : <ul className="tc-notices">
        {mine.map(item => <li key={item.id}>
          <span className="tc-notice-icon"><Icon name="announcements" /></span>
          <div className="tc-notice-body">
            <div className="tc-notice-head"><strong>{item.title}</strong><span className="tc-audience">{item.audience}</span><small>{item.date}</small></div>
            <p>{item.message}</p>
            <div className="tc-notice-foot">
              <span><Icon name="check" />Published by you</span>
              <button type="button" className="sa-ghost sa-danger" onClick={() => { setAnnouncements(current => current.filter(row => row.id !== item.id)); log("Announcement withdrawn", item.title); say("Announcement withdrawn."); }}>Withdraw</button>
            </div>
          </div>
        </li>)}
      </ul>}
    </Panel>

    <Panel title="From the administration" icon="bell" note="Read-only. Published to a wider authorized audience." wide>
      {fromAdmin.length === 0 ? <Empty text="Nothing from the administration right now." /> : <ul className="tc-notices">
        {fromAdmin.map(item => <li key={item.id}>
          <span className="tc-notice-icon tint-lilac"><Icon name="bell" /></span>
          <div className="tc-notice-body">
            <div className="tc-notice-head"><strong>{item.title}</strong><span className="tc-audience">{item.audience}</span><small>{item.date}</small></div>
            <p>{item.message}</p>
          </div>
        </li>)}
      </ul>}
    </Panel>

    {composing && <Modal title="New section announcement" note={`Audience: ${audience}. Keep operational messages separate from simulated emergency activities.`} onClose={() => setComposing(false)}>
      <form className="sa-form" onSubmit={event => {
        event.preventDefault();
        const data = new FormData(event.currentTarget);
        const title = String(data.get("title"));
        setAnnouncements(current => [{ id: `an${Date.now()}`, title, message: String(data.get("message")), audience, date: "Sep 18, 2026" }, ...current]);
        log("Section announcement published", `${title} · ${audience}`);
        say(`Published to ${audience}.`);
        setComposing(false);
      }}>
        <Field label="Title"><input name="title" required placeholder="What is this about?" /></Field>
        <Field label="Audience"><input value={audience} readOnly /></Field>
        <Field label="Message" hint="No student tokens, names, or results in an announcement."><textarea name="message" rows={4} required placeholder="Keep it short and actionable." /></Field>
        <button type="submit" className="sa-primary">Publish announcement<Icon name="arrow" /></button>
      </form>
    </Modal>}
  </div>;
}

export function TeacherConsent() {
  const store = useData();
  const { users, links, setLinks, setUsers, settings, log, say } = store;
  const scope = useScope();
  const [inviting, setInviting] = useState(false);
  const roster = users.filter(user => user.role === "Student" && user.section === scope.sectionId);
  const myLinks = links.filter(link => roster.some(student => student.id === link.studentId));
  const parents = users.filter(user => user.role === "Parent" && user.status === "Active");
  const pending = myLinks.filter(link => link.status === "Pending");

  return <div className="tc-page">
    <PageHead icon="consent" eyebrow="Consent & parent links" title={store.sectionOf(scope.sectionId)}
      actions={<button type="button" className="sa-primary" onClick={() => setInviting(true)}><Icon name="mail" />Issue guardian invitation</button>}>
      You are the responsible verifier for this section. Verification happens in person or through the approved offline process — never through this screen alone.
    </PageHead>

    <div className="tc-metrics tc-metrics-4">
      <Metric icon="check" tint="mint" label="Consent verified" value={roster.filter(student => student.consent).length} sub={`of ${roster.length}`}>
        A parent signed the paper form. {settings.noticeVersion} is the version on file.
      </Metric>
      <Metric icon="person" tint="lilac" label="Assent recorded" value={roster.filter(student => student.assent).length} sub={`of ${roster.length}`}>
        The child said yes themselves in the mobile app. A child can decline even when their parent signed.
      </Metric>
      <Metric icon="users" tint="blue" label="Active guardian links" value={myLinks.filter(link => link.status === "Active").length}>
        Verified relationships in this section. A parent sees only the children listed here.
      </Metric>
      <Metric icon="bell" tint="coral" label="Awaiting your verification" value={pending.length} flag={pending.length > 0}>
        {pending.length ? "Nobody sees anything until you confirm in person that this is really the parent." : "Nothing is waiting. Every request has been confirmed or turned down."}
      </Metric>
    </div>

    <Panel title="Physical consent status" icon="consent" note="Online acknowledgment never replaces mandatory physical informed consent." wide>
      <div className="tc-table-scroll"><table className="sa-table">
        <thead><tr><th>Token</th><th>Physical consent</th><th>Child assent</th><th>Notice version</th><th /></tr></thead>
        <tbody>{roster.map(student => <tr key={student.id}>
          <td className="sa-mono">{student.name}</td>
          <td>{student.consent ? <Pill>Verified</Pill> : <Pill>Pending</Pill>}</td>
          <td>{student.assent ? <Pill>Active</Pill> : <Pill>Pending</Pill>}</td>
          <td className="sa-dim">{settings.noticeVersion}</td>
          <td className="sa-cell-actions">
            {!student.consent && <button type="button" className="sa-ghost" onClick={() => { setUsers(current => current.map(row => (row.id === student.id ? { ...row, consent: true } : row))); log("Consent verified", `${student.name} · physical form verified by ${scope.teacherName}`); say("Consent recorded. Only the verification metadata is stored, never a scan of the signed form."); }}><Icon name="check" />Record verification</button>}
          </td>
        </tr>)}</tbody>
      </table></div>
      <Note>The website stores verification status, date, verifier, and notice version — not scans of signed forms or identification documents.</Note>
    </Panel>

    <Panel title="Guardian relationships" icon="users" note="An expiring, one-time invitation is issued for one student record and redeemed by an authenticated parent." wide>
      {myLinks.length === 0 ? <Empty text="No guardian links requested for this section." /> : <div className="tc-table-scroll"><table className="sa-table tc-table-mid">
        <thead><tr><th>Parent account</th><th>Student token</th><th>State</th><th>Verified by</th><th /></tr></thead>
        <tbody>{myLinks.map(link => <tr key={link.id}>
          <td><strong>{store.nameOf(link.parentId)}</strong><small className="sa-cell-sub">{users.find(user => user.id === link.parentId)?.email}</small></td>
          <td className="sa-mono">{store.nameOf(link.studentId)}</td>
          <td><Pill>{link.status}</Pill></td>
          <td>{link.verifiedBy || <span className="sa-dim">Awaiting your confirmation</span>}</td>
          <td className="sa-cell-actions">
            {link.status === "Pending" && <button type="button" className="sa-ghost" onClick={() => { setLinks(current => current.map(row => (row.id === link.id ? { ...row, status: "Active", verifiedBy: scope.teacherName } : row))); log("Guardian link confirmed", `${store.nameOf(link.parentId)} · ${store.nameOf(link.studentId)}`); say("Link activated. The parent and you both receive an access confirmation."); }}><Icon name="check" />Confirm account</button>}
            {link.status !== "Revoked" && <button type="button" className="sa-ghost sa-danger" onClick={() => { setLinks(current => current.map(row => (row.id === link.id ? { ...row, status: "Revoked" } : row))); log("Guardian link revoked", `${store.nameOf(link.parentId)} · ${store.nameOf(link.studentId)}`); say("Access revoked immediately. The child records and other guardians are unaffected."); }}>Revoke</button>}
          </td>
        </tr>)}</tbody>
      </table></div>}
    </Panel>

    <Panel title="Why you have to confirm in person" icon="bell" note="These are the things people assume prove someone is a parent. None of them do." wide>
      <ul className="tc-limits">
        <li><span><Icon name="close" /></span><div><strong>Knowing the token</strong><small>Tokens get written on paper, shared in group chats, and seen by classmates.</small></div></li>
        <li><span><Icon name="close" /></span><div><strong>Having the same surname</strong><small>Plenty of unrelated people share a surname, and plenty of families do not.</small></div></li>
        <li><span><Icon name="close" /></span><div><strong>Knowing the class code</strong><small>Every child in the class knows it, so it proves nothing about one person.</small></div></li>
        <li><span><Icon name="close" /></span><div><strong>Holding the child device</strong><small>A phone can be borrowed, lost, or taken. It is not the same as being the parent.</small></div></li>
      </ul>
      <Note>You cannot revoke a guardian relationship in another teacher section. Revoking access here stops one adult from seeing one child; it does not withdraw the child from the study.</Note>
    </Panel>

    {inviting && <Modal title="Issue a guardian invitation" note="Verify the physical consent and the guardian relationship offline first." onClose={() => setInviting(false)}>
      <form className="sa-form" onSubmit={event => {
        event.preventDefault();
        const data = new FormData(event.currentTarget);
        const studentId = String(data.get("student"));
        const parentId = String(data.get("parent"));
        setLinks(current => [...current, { id: `l${Date.now()}`, parentId, studentId, status: "Pending", verifiedBy: "" }]);
        log("Guardian invitation issued", `${store.nameOf(parentId)} · ${store.nameOf(studentId)} · issued by ${scope.teacherName}`);
        say("One-time invitation issued. It expires, is single-use, and is tied to one student record.");
        setInviting(false);
      }}>
        <Field label="Student token"><select name="student" required>{roster.map(student => <option key={student.id} value={student.id}>{student.name}</option>)}</select></Field>
        <Field label="Verified parent account" hint="Confirm this is the intended adult before the backend activates the relationship."><select name="parent" required>{parents.map(parent => <option key={parent.id} value={parent.id}>{parent.name} · {parent.email}</option>)}</select></Field>
        <label className="sa-check"><input type="checkbox" required /><span>I verified the physical consent form and the guardian relationship offline</span></label>
        <button type="submit" className="sa-primary">Issue invitation<Icon name="arrow" /></button>
      </form>
    </Modal>}
  </div>;
}

export function MyAccount() {
  const store = useData();
  const { users, sections, say, log } = store;
  const scope = useScope();
  const teacher = users.find(user => user.id === scope.teacherId);

  return <div className="tc-page">
    <PageHead icon="settings" eyebrow="My account" title={teacher?.name ?? "Teacher"}>
      Your own profile and preferences. Your role and your section assignments are controlled by a Super Admin — a teacher cannot grant either to themselves.
    </PageHead>

    <div className="tc-grid-2">
      <Panel title="Profile" icon="person" note="You can update your own details and password.">
        <Field label="Full name"><input defaultValue={teacher?.name} /></Field>
        <Field label="Email address" hint="Changing this requires re-verification."><input defaultValue={teacher?.email} type="email" /></Field>
        <Field label="New password" hint="At least 8 characters. Stored as a salted hash, never in reversible form."><input type="password" placeholder="Leave blank to keep the current password" /></Field>
        <div className="sa-action-row"><button type="button" className="sa-primary" onClick={() => { log("Profile updated", `${teacher?.name} updated their own profile`); say("Profile saved."); }}><Icon name="check" />Save profile</button></div>
      </Panel>

      <Panel title="Access and notifications" icon="consent" note="What you are authorized to see, and what reaches your inbox.">
        <ul className="sa-list">
          <li><div><strong>Assigned sections</strong><small>{sections.filter(section => section.teacherId === scope.teacherId).map(section => section.name).join(" · ") || "None"}</small></div><Pill>Active</Pill></li>
          <li><div><strong>Account role</strong><small>Teacher · one role per adult account in this release</small></div><Pill>Active</Pill></li>
          <li><div><strong>Multi-factor authentication</strong><small>Optional for teachers, required for administrators</small></div><Pill>Pending</Pill></li>
        </ul>
        <h3 className="sa-sub">Notification preferences</h3>
        <label className="sa-check"><input type="checkbox" defaultChecked /><span>A practical assessment was submitted in my section</span></label>
        <label className="sa-check"><input type="checkbox" defaultChecked /><span>A guardian link is awaiting my verification</span></label>
        <label className="sa-check"><input type="checkbox" defaultChecked /><span>A content draft I submitted received a decision</span></label>
        <Note>Notification emails carry a generic message. Detailed child results require you to sign in.</Note>
      </Panel>
    </div>

    <Panel title="What this role cannot do" icon="audit" note="Enforced on the backend, not by hiding a menu item." wide>
      <ul className="tc-limits">
        <li><span><Icon name="close" /></span><div><strong>Reach another section</strong><small>Not by URL, filter, export, or attachment ID — only your assigned sections resolve.</small></div></li>
        <li><span><Icon name="close" /></span><div><strong>Change adult roles</strong><small>You cannot approve your own account or assign yourself a section.</small></div></li>
        <li><span><Icon name="close" /></span><div><strong>See another teacher master list</strong><small>The token-to-name mapping stays with the teacher who holds the section.</small></div></li>
        <li><span><Icon name="close" /></span><div><strong>Publish a global protocol change</strong><small>Baseline safety procedures go through authorized review first.</small></div></li>
        <li><span><Icon name="close" /></span><div><strong>Delete research logs</strong><small>Audit entries are immutable, and another section guardian link is not yours to revoke.</small></div></li>
        <li><span><Icon name="close" /></span><div><strong>Edit raw attempts or grant XP</strong><small>Corrections follow the revision workflow and keep their history.</small></div></li>
      </ul>
    </Panel>
  </div>;
}
